# Generated by Django 5.1.4 on 2025-01-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmessage',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaintmessage',
            name='tmethod',
            field=models.CharField(blank=True, max_length=200, verbose_name='Transfer method'),
        ),
    ]
